import Link from "next/link";
import { BrainCircuit, FileText, Search, Sparkles } from "lucide-react";
import { Badge, PageHeader } from "@/components/page-parts";
import { DocumentUpload } from "@/components/document-upload";
import { getDocuments } from "@/lib/repositories";

export default async function KnowledgePage() {
  const documents = await getDocuments();
  return <div><PageHeader eyebrow="Acervo TSP conectado" title="Base de Inteligência" description="Documentos, ICPs, campanhas, manual de equipe, rotinas, logos e síntese estratégica em uma única fonte." action={<DocumentUpload />} /><div className="panel mb-6 flex items-center gap-3 p-3"><Search className="ml-2 size-5 text-slate-400" /><input className="h-10 flex-1 outline-none" placeholder="Buscar método, ICP, campanha, professor, oferta..." /><button className="flex h-10 items-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white"><BrainCircuit className="size-4" />Perguntar à IA</button></div><div className="mb-6 grid gap-4 md:grid-cols-3"><Link className="panel panel-interactive p-5" href="/app/marca/codigo-tsp"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-emerald-700">Doutrina</p><h2 className="mt-3 font-heading text-lg font-semibold">Código TSP</h2><p className="muted mt-2 text-sm">Identidade, Movimento e Método como núcleo do projeto.</p></Link><Link className="panel panel-interactive p-5" href="/app/marca/alunos"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-emerald-700">ICP</p><h2 className="mt-3 font-heading text-lg font-semibold">Ricardo, Antônio e Carla</h2><p className="muted mt-2 text-sm">Três jornadas de desejo, dor e transformação.</p></Link><Link className="panel panel-interactive p-5" href="/app/marca/gamificacao"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-emerald-700">Comunidade</p><h2 className="mt-3 font-heading text-lg font-semibold">Gamificação antirrecaída</h2><p className="muted mt-2 text-sm">Missões, pontos, ritos e checkpoints de pertencimento.</p></Link></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{documents.map((document) => <article key={document.title} className="panel p-5"><div className="flex items-center justify-between"><div className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><FileText /></div><button aria-label="Gerar resumo"><Sparkles className="size-5 text-emerald-600" /></button></div><h2 className="mt-5 font-heading font-semibold">{document.title}</h2><p className="mt-2 text-sm text-slate-500">{document.type}</p><div className="mt-5 flex flex-wrap gap-2">{document.tags.map((tag: string) => <Badge key={tag}>{tag}</Badge>)}</div></article>)}</div></div>;
}
